// This file is auto-generated by scripts/build-mcp-servers.mjs.

// Do not edit it manually. To regenerate after changing integrations/catalog/*.json,

// run: npm run build:mcp-servers

import entry0 from "./airtable.json" with { type: "json" };
import entry1 from "./apify.json" with { type: "json" };
import entry2 from "./atlassian.json" with { type: "json" };
import entry3 from "./atlassian-rovo.json" with { type: "json" };
import entry4 from "./brave-search.json" with { type: "json" };
import entry5 from "./browser-mcp.json" with { type: "json" };
import entry6 from "./clickhouse.json" with { type: "json" };
import entry7 from "./cloudflare-bindings.json" with { type: "json" };
import entry8 from "./cloudflare-browser-rendering.json" with { type: "json" };
import entry9 from "./cloudflare-builds.json" with { type: "json" };
import entry10 from "./cloudflare-docs.json" with { type: "json" };
import entry11 from "./cloudflare-observability.json" with { type: "json" };
import entry12 from "./datadog.json" with { type: "json" };
import entry13 from "./deepwiki.json" with { type: "json" };
import entry14 from "./everything.json" with { type: "json" };
import entry15 from "./exa.json" with { type: "json" };
import entry16 from "./fetch.json" with { type: "json" };
import entry17 from "./figma.json" with { type: "json" };
import entry18 from "./filesystem.json" with { type: "json" };
import entry19 from "./firecrawl.json" with { type: "json" };
import entry20 from "./git.json" with { type: "json" };
import entry21 from "./github.json" with { type: "json" };
import entry22 from "./gitlab.json" with { type: "json" };
import entry23 from "./granola.json" with { type: "json" };
import entry24 from "./hubspot.json" with { type: "json" };
import entry25 from "./huggingface.json" with { type: "json" };
import entry26 from "./kagi.json" with { type: "json" };
import entry27 from "./linear.json" with { type: "json" };
import entry28 from "./memory.json" with { type: "json" };
import entry29 from "./miro.json" with { type: "json" };
import entry30 from "./monday.json" with { type: "json" };
import entry31 from "./mongodb.json" with { type: "json" };
import entry32 from "./neon.json" with { type: "json" };
import entry33 from "./notion.json" with { type: "json" };
import entry34 from "./obsidian.json" with { type: "json" };
import entry35 from "./ordinal.json" with { type: "json" };
import entry36 from "./paypal.json" with { type: "json" };
import entry37 from "./playwright.json" with { type: "json" };
import entry38 from "./posthog.json" with { type: "json" };
import entry39 from "./redis.json" with { type: "json" };
import entry40 from "./reportportal.json" with { type: "json" };
import entry41 from "./resend.json" with { type: "json" };
import entry42 from "./salesforce.json" with { type: "json" };
import entry43 from "./sentry.json" with { type: "json" };
import entry44 from "./sequential-thinking.json" with { type: "json" };
import entry45 from "./slack.json" with { type: "json" };
import entry46 from "./sonarqube.json" with { type: "json" };
import entry47 from "./stripe.json" with { type: "json" };
import entry48 from "./supabase.json" with { type: "json" };
import entry49 from "./superhuman-mail.json" with { type: "json" };
import entry50 from "./tavily.json" with { type: "json" };
import entry51 from "./time.json" with { type: "json" };
import entry52 from "./vanta.json" with { type: "json" };
import entry53 from "./webflow.json" with { type: "json" };

export const MCP_SERVER_ARTIFACTS = [
  entry0,
  entry1,
  entry2,
  entry3,
  entry4,
  entry5,
  entry6,
  entry7,
  entry8,
  entry9,
  entry10,
  entry11,
  entry12,
  entry13,
  entry14,
  entry15,
  entry16,
  entry17,
  entry18,
  entry19,
  entry20,
  entry21,
  entry22,
  entry23,
  entry24,
  entry25,
  entry26,
  entry27,
  entry28,
  entry29,
  entry30,
  entry31,
  entry32,
  entry33,
  entry34,
  entry35,
  entry36,
  entry37,
  entry38,
  entry39,
  entry40,
  entry41,
  entry42,
  entry43,
  entry44,
  entry45,
  entry46,
  entry47,
  entry48,
  entry49,
  entry50,
  entry51,
  entry52,
  entry53,
];
