#!/usr/bin/env python3
"""Sync Claude Code command files from OpenHands slash triggers.

For every SKILL.md that declares a slash-trigger (e.g. ``/init``), this
script ensures a matching ``commands/<trigger>.md`` file exists in the
same skill/plugin directory.  The command file is a thin wrapper that
tells Claude Code to read the accompanying SKILL.md.

Usage:
    python scripts/sync_claude_commands.py              # generate / update
    python scripts/sync_claude_commands.py --check      # CI mode — exit 1 if out of sync
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

HEADER = "<!-- AUTO-GENERATED by scripts/sync_claude_commands.py — DO NOT EDIT -->\n"

SKILL_DIRS = [
    REPO_ROOT / "skills",
    REPO_ROOT / "plugins",
]


# ---------------------------------------------------------------------------
# Frontmatter helpers
# ---------------------------------------------------------------------------

def parse_frontmatter(text: str) -> dict[str, str | list[str]]:
    """Return a minimal dict with *name*, *description*, and *triggers*."""
    m = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not m:
        return {}
    block = m.group(1)

    result: dict[str, str | list[str]] = {}

    # name / description — single-line scalars
    for key in ("name", "description"):
        km = re.search(rf"^{key}:\s*(.+)$", block, re.MULTILINE)
        if km:
            result[key] = km.group(1).strip()

    # triggers — YAML list
    triggers: list[str] = []
    in_triggers = False
    for line in block.splitlines():
        if line.startswith("triggers:"):
            in_triggers = True
            continue
        if in_triggers:
            stripped = line.strip()
            if stripped.startswith("- "):
                triggers.append(stripped[2:].strip())
            else:
                break
    result["triggers"] = triggers
    return result


def slash_triggers(meta: dict) -> list[str]:
    """Return trigger values that start with ``/``."""
    return [t for t in meta.get("triggers", []) if isinstance(t, str) and t.startswith("/")]


# ---------------------------------------------------------------------------
# Command-file generation
# ---------------------------------------------------------------------------

def build_command_content(trigger: str, description: str) -> str:
    """Build the Markdown for a Claude Code command file."""
    lines = [
        HEADER,
        "---",
        f"description: {description}",
        "---",
        "",
        "Read and follow the complete instructions in the SKILL.md file located in this skill's directory.",
        "",
        "$ARGUMENTS",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def collect_needed_commands() -> list[tuple[Path, str, str]]:
    """Return ``(command_path, trigger, description)`` for every slash trigger."""
    needed: list[tuple[Path, str, str]] = []
    for base in SKILL_DIRS:
        if not base.is_dir():
            continue
        for skill_dir in sorted(base.iterdir()):
            skill_md = skill_dir / "SKILL.md"
            if not skill_md.is_file():
                continue
            meta = parse_frontmatter(skill_md.read_text())
            desc = meta.get("description", "")
            for trigger in slash_triggers(meta):
                cmd_name = trigger.lstrip("/")
                cmd_path = skill_dir / "commands" / f"{cmd_name}.md"
                needed.append((cmd_path, trigger, desc))
    return needed


def sync(*, check: bool = False) -> int:
    """Generate (or check) command files.  Returns exit code."""
    needed = collect_needed_commands()
    if not needed:
        print("No slash triggers found — nothing to do.")
        return 0

    missing: list[Path] = []
    stale: list[Path] = []

    for cmd_path, trigger, description in needed:
        expected = build_command_content(trigger, description)
        if cmd_path.is_file():
            existing = cmd_path.read_text()
            if existing == expected:
                continue
            # Only update auto-generated files (check for our header)
            if HEADER in existing:
                stale.append(cmd_path)
            # Leave manually-authored command files alone
        else:
            missing.append(cmd_path)

        if not check:
            cmd_path.parent.mkdir(parents=True, exist_ok=True)
            # Only write if missing or auto-generated (stale)
            if cmd_path in missing or cmd_path in stale:
                cmd_path.write_text(expected)

    if check:
        problems = missing + stale
        if problems:
            print("Claude Code command files out of sync:")
            for p in sorted(problems):
                label = "missing" if p in missing else "stale"
                print(f"  {label}: {p.relative_to(REPO_ROOT)}")
            print(f"\nRun `python scripts/sync_claude_commands.py` to fix.")
            return 1
        print("All Claude Code command files are in sync.")
        return 0

    written = missing + stale
    if written:
        for p in sorted(written):
            print(f"  wrote: {p.relative_to(REPO_ROOT)}")
        print(f"\n{len(written)} command file(s) written.")
    else:
        print("All command files already up to date.")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check mode: exit 1 if any command files are missing or stale (for CI).",
    )
    args = parser.parse_args()
    sys.exit(sync(check=args.check))
