#!/usr/bin/env python3
"""Keep the OpenHands extensions registry in sync.

Four responsibilities, runnable individually or all at once:

  1. **commands**  — generate Claude Code ``commands/<trigger>.md`` files from
     SKILL.md slash-triggers.
  2. **catalog**   — regenerate the auto-generated catalog section in README.md.
  3. **coverage**  — warn (or fail) when a skill/plugin directory is not listed
     in any marketplace, or a marketplace entry points to a missing directory.
  4. **symlinks**  — enforce that every plugin has ``.plugin/plugin.json`` as the
     source of truth and vendor symlinks (``.claude-plugin``, ``.codex-plugin``)
     pointing to it.

Usage:
    python scripts/sync_extensions.py                   # run all, write changes
    python scripts/sync_extensions.py --check           # CI mode — exit 1 if anything is out of sync
    python scripts/sync_extensions.py commands           # only sync command files
    python scripts/sync_extensions.py catalog            # only regenerate README catalog
    python scripts/sync_extensions.py coverage           # only check marketplace coverage
    python scripts/sync_extensions.py symlinks           # only check/fix vendor symlinks
    python scripts/sync_extensions.py commands catalog   # combine sub-commands
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
README_PATH = REPO_ROOT / "README.md"
SKILL_DIRS = [REPO_ROOT / "skills", REPO_ROOT / "plugins"]
MARKETPLACES_DIR = REPO_ROOT / "marketplaces"

# Vendor symlink names that must point to .plugin/ in every plugin directory.
# Add new vendors here as they adopt plugin support.
VENDOR_SYMLINKS = [".claude-plugin", ".codex-plugin"]

# Sentinel markers in README.md
CATALOG_BEGIN = "<!-- BEGIN AUTO-GENERATED CATALOG -->"
CATALOG_END = "<!-- END AUTO-GENERATED CATALOG -->"

# Header for auto-generated Claude Code command files
CMD_HEADER = "<!-- AUTO-GENERATED by scripts/sync_extensions.py — DO NOT EDIT -->\n"
# Also recognize the legacy header from the old script
_LEGACY_CMD_HEADER = "<!-- AUTO-GENERATED by scripts/sync_claude_commands.py — DO NOT EDIT -->\n"


# ── Frontmatter helpers ──────────────────────────────────────────────

def parse_frontmatter(text: str) -> dict[str, str | list[str]]:
    m = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not m:
        return {}
    block = m.group(1)
    result: dict[str, str | list[str]] = {}
    for key in ("name", "description"):
        km = re.search(rf"^{key}:\s*(.+)$", block, re.MULTILINE)
        if km:
            result[key] = km.group(1).strip()
    triggers: list[str] = []
    in_triggers = False
    for line in block.splitlines():
        if line.startswith("triggers:"):
            in_triggers = True
            continue
        if in_triggers:
            stripped = line.strip()
            if stripped.startswith("- "):
                triggers.append(stripped[2:].strip())
            else:
                break
    result["triggers"] = triggers
    return result


def slash_triggers(meta: dict) -> list[str]:
    return [t for t in meta.get("triggers", []) if isinstance(t, str) and t.startswith("/")]


# ── Marketplace loading ──────────────────────────────────────────────

def load_marketplaces() -> list[dict]:
    """Return list of parsed marketplace dicts, sorted by filename."""
    mps = []
    for mp_file in sorted(MARKETPLACES_DIR.glob("*.json")):
        with open(mp_file) as f:
            data = json.load(f)
        data["_file"] = mp_file
        mps.append(data)
    return mps


# ── 1. Claude Code command sync ──────────────────────────────────────

def build_command_content(description: str) -> str:
    lines = [
        CMD_HEADER,
        "---",
        f"description: {description}",
        "---",
        "",
        "Read and follow the complete instructions in the SKILL.md file located in this skill's directory.",
        "",
        "$ARGUMENTS",
        "",
    ]
    return "\n".join(lines)


def collect_needed_commands() -> list[tuple[Path, str, str]]:
    """Return ``(command_path, trigger, description)`` for every slash trigger."""
    needed: list[tuple[Path, str, str]] = []
    for base in SKILL_DIRS:
        if not base.is_dir():
            continue
        for skill_dir in sorted(base.iterdir()):
            skill_md = skill_dir / "SKILL.md"
            if not skill_md.is_file():
                continue
            meta = parse_frontmatter(skill_md.read_text())
            desc = str(meta.get("description", ""))
            for trigger in slash_triggers(meta):
                cmd_name = trigger.lstrip("/")
                cmd_path = skill_dir / "commands" / f"{cmd_name}.md"
                needed.append((cmd_path, trigger, desc))
    return needed


def sync_commands(*, check: bool) -> list[str]:
    """Returns list of problem descriptions (empty = all good)."""
    problems: list[str] = []
    for cmd_path, trigger, description in collect_needed_commands():
        expected = build_command_content(description)
        if cmd_path.is_file():
            existing = cmd_path.read_text()
            if existing == expected:
                continue
            if CMD_HEADER not in existing and _LEGACY_CMD_HEADER not in existing:
                # manually authored — skip
                continue
            problems.append(f"stale: {cmd_path.relative_to(REPO_ROOT)}")
        else:
            problems.append(f"missing: {cmd_path.relative_to(REPO_ROOT)}")

        if not check:
            cmd_path.parent.mkdir(parents=True, exist_ok=True)
            cmd_path.write_text(expected)

    return problems


# ── 2. README catalog generation ─────────────────────────────────────

def _entry_type(source: str) -> str:
    if source.startswith("./skills/"):
        return "skill"
    if source.startswith("./plugins/"):
        return "plugin"
    return "unknown"


def _get_slash_commands(source: str) -> list[str]:
    """Read SKILL.md from source path to extract slash triggers."""
    skill_md = REPO_ROOT / source.lstrip("./") / "SKILL.md"
    if not skill_md.is_file():
        return []
    meta = parse_frontmatter(skill_md.read_text())
    return slash_triggers(meta)


def generate_catalog() -> str:
    """Build the Markdown catalog section."""
    mps = load_marketplaces()
    total_skills = 0
    total_plugins = 0

    for mp in mps:
        for p in mp.get("plugins", []):
            t = _entry_type(p.get("source", ""))
            if t == "skill":
                total_skills += 1
            elif t == "plugin":
                total_plugins += 1

    lines: list[str] = [""]
    lines.append(
        f"This repository contains **{len(mps)} marketplace(s)** "
        f"with **{total_skills} skills** and **{total_plugins} plugins**."
    )
    lines.append("")

    for mp in mps:
        mp_name = mp.get("name", mp["_file"].stem)
        mp_desc = mp.get("metadata", {}).get("description", "")
        plugins = mp.get("plugins", [])
        skill_count = sum(1 for p in plugins if _entry_type(p.get("source", "")) == "skill")
        plugin_count = sum(1 for p in plugins if _entry_type(p.get("source", "")) == "plugin")

        lines.append(f"### {mp_name}")
        lines.append("")
        if mp_desc:
            lines.append(mp_desc)
            lines.append("")
        lines.append(f"**{skill_count} skills, {plugin_count} plugins**")
        lines.append("")
        lines.append("```bash")
        lines.append(f"claude plugins add-marketplace https://github.com/OpenHands/extensions  # registers \"{mp_name}\"")
        lines.append("```")
        lines.append("")

        # Table
        lines.append("| Name | Type | Description | Commands |")
        lines.append("|------|------|-------------|----------|")
        for p in sorted(plugins, key=lambda x: x["name"]):
            name = p["name"]
            etype = _entry_type(p.get("source", ""))
            desc = (p.get("description") or "").replace("|", "\\|")
            # Truncate long descriptions for the table
            if len(desc) > 120:
                desc = desc[:117] + "..."
            cmds = _get_slash_commands(p.get("source", ""))
            cmds_str = ", ".join(f"`{c}`" for c in cmds) if cmds else "—"
            lines.append(f"| {name} | {etype} | {desc} | {cmds_str} |")

        lines.append("")

    return "\n".join(lines)


def sync_catalog(*, check: bool) -> list[str]:
    """Returns list of problem descriptions (empty = all good)."""
    if not README_PATH.is_file():
        return ["README.md not found"]

    readme = README_PATH.read_text()
    if CATALOG_BEGIN not in readme or CATALOG_END not in readme:
        return [
            f"README.md missing catalog markers ({CATALOG_BEGIN} / {CATALOG_END}). "
            "Add them where the catalog should appear."
        ]

    before = readme[: readme.index(CATALOG_BEGIN) + len(CATALOG_BEGIN)]
    after = readme[readme.index(CATALOG_END) :]
    existing_catalog = readme[len(before) : readme.index(CATALOG_END)]

    new_catalog = generate_catalog()

    if existing_catalog == new_catalog:
        return []

    if check:
        return ["README.md catalog section is out of date"]

    README_PATH.write_text(before + new_catalog + after)
    return []


# ── 3. Marketplace coverage ─────────────────────────────────────────

def sync_coverage(*, check: bool) -> list[str]:
    """Check that every directory is in a marketplace and vice versa."""
    # Collect all dirs with SKILL.md or .plugin/plugin.json (or vendor symlinks like .claude-plugin)
    all_dirs: set[str] = set()
    for base in SKILL_DIRS:
        if not base.is_dir():
            continue
        for d in base.iterdir():
            if not d.is_dir() or d.name.startswith("."):
                continue
            has_skill = (d / "SKILL.md").exists()
            has_plugin = (
                (d / ".claude-plugin" / "plugin.json").exists()
                or (d / ".plugin" / "plugin.json").exists()
            )
            if has_skill or has_plugin:
                all_dirs.add(f"./{base.name}/{d.name}")

    # Collect all marketplace sources
    all_sources: set[str] = set()
    for mp in load_marketplaces():
        for p in mp.get("plugins", []):
            all_sources.add(p.get("source", ""))

    problems: list[str] = []

    missing_from_mp = sorted(all_dirs - all_sources)
    for d in missing_from_mp:
        problems.append(f"not in any marketplace: {d}")

    ghost_entries = sorted(all_sources - all_dirs)
    for s in ghost_entries:
        p = REPO_ROOT / s.lstrip("./")
        if not p.is_dir():
            problems.append(f"marketplace entry points to missing directory: {s}")
        else:
            problems.append(f"marketplace entry has no SKILL.md or plugin.json: {s}")

    return problems


# ── 4. Plugin symlink enforcement ─────────────────────────────────────

def _plugin_dirs() -> list[Path]:
    """Return plugin directories that have .plugin/plugin.json."""
    plugins_root = REPO_ROOT / "plugins"
    if not plugins_root.is_dir():
        return []
    return sorted(
        d for d in plugins_root.iterdir()
        if d.is_dir()
        and not d.name.startswith(".")
        and (d / ".plugin" / "plugin.json").exists()
    )


def sync_symlinks(*, check: bool) -> list[str]:
    """Ensure every plugin has .plugin/plugin.json and vendor symlinks.

    In check mode, report problems without fixing them.
    In write mode, create missing symlinks automatically.
    """
    problems: list[str] = []
    plugins_root = REPO_ROOT / "plugins"
    if not plugins_root.is_dir():
        return problems

    for d in sorted(plugins_root.iterdir()):
        if not d.is_dir() or d.name.startswith("."):
            continue

        source_of_truth = d / ".plugin" / "plugin.json"
        if not source_of_truth.exists():
            # No .plugin/plugin.json — this plugin has no manifest at all.
            # Only flag it if the dir looks like a real plugin (has skills/ or README).
            if (d / "skills").is_dir() or (d / "README.md").exists():
                problems.append(
                    f"plugins/{d.name}: missing .plugin/plugin.json (source of truth)"
                )
            continue

        for vendor in VENDOR_SYMLINKS:
            link_path = d / vendor
            if link_path.is_symlink():
                target = os.readlink(link_path)
                if target != ".plugin":
                    problems.append(
                        f"plugins/{d.name}/{vendor}: symlink points to '{target}', expected '.plugin'"
                    )
            elif link_path.exists():
                # It's a real directory, not a symlink
                problems.append(
                    f"plugins/{d.name}/{vendor}: is a real directory, should be a symlink to .plugin"
                )
            else:
                # Missing symlink
                if check:
                    problems.append(
                        f"plugins/{d.name}/{vendor}: missing symlink → .plugin"
                    )
                else:
                    link_path.symlink_to(".plugin")

    return problems


# ── Main ─────────────────────────────────────────────────────────────

ALL_SYNCS = {
    "commands": sync_commands,
    "catalog": sync_catalog,
    "coverage": sync_coverage,
    "symlinks": sync_symlinks,
}


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Keep the OpenHands extensions registry in sync.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "tasks",
        nargs="*",
        choices=[*ALL_SYNCS.keys(), []],
        default=[],
        help="Which sync tasks to run (default: all).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check mode: exit 1 if anything is out of sync (for CI).",
    )
    args = parser.parse_args()
    tasks = args.tasks or list(ALL_SYNCS.keys())

    all_problems: dict[str, list[str]] = {}
    for task in tasks:
        fn = ALL_SYNCS[task]
        problems = fn(check=args.check)
        if problems:
            all_problems[task] = problems

    if all_problems:
        for task, problems in all_problems.items():
            severity = "warning" if task == "coverage" else "error"
            print(f"\n[{severity}] {task}:")
            for p in problems:
                print(f"  {p}")
        if args.check:
            has_errors = any(k != "coverage" for k in all_problems)
            has_warnings = "coverage" in all_problems
            if has_errors:
                print(f"\nRun `python scripts/sync_extensions.py` to fix.")
                return 1
            if has_warnings:
                # Coverage warnings don't fail CI, just warn
                print(f"\n⚠️  Coverage warnings above are non-blocking.")
                return 0
        else:
            print("\nSync complete.")
        return 0

    if args.check:
        print("All extensions in sync. ✓")
    else:
        print("Everything already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
